function writeFile(data, inst_ang_vel, inst_ang_acc, slow_phase_matrix, summary, saved_file)
%UNTITLED6 Summary of this function goes here
%   Detailed explanation goes here
    
    
    %Check if this file already exists. If so, delete it so that it is
    %replaced, not rewritten.
    if exist(saved_file, 'file')
        delete(saved_file);
    end
    %filename = strcat(filename, '.xlsx')
    excel_file = saved_file;
    
    %Summary sheet:
    labels_summ = {'Date of Recording'; 'Date of Processing'; 'Sample Genotype'; ...
        'Date of Birth'; 'Age (dpf)'; 'Stimulus Velocity (deg/s)'; 'Stimulus Direction'; 'Number of Bands'; ...
        'Angle Moving Average Window'; 'Velocity Moving Average Window';...
        'Acceleration Moving Average Window'; 'Steady State Buffer'; ...
        'Usable Range of Original Recording (s)';...
        'Average Slow Phase Angular Velocity Left (deg/s)'; ...
        'Average Slow Phase Angular Velocity Right (deg/s)';...
        'Average Slow Phase Gain Left'; 'Average Slow Phase Gain Right'; ...
        'Average Ocular Range Left'; 'Average Ocular Range Right'};
    writecell(labels_summ, excel_file, 'Sheet', 'Summary', 'Range', 'A2');
    writecell(summary, excel_file, 'Sheet', 'Summary', 'Range', 'B2');
    
    %Raw data sheet:
    labels_raw = {'Time (s)', 'Raw Left Eye Angles', 'Raw Right Eye Angles', ...
        'Smoothed Left Eye Angles', 'Smoothed Right Eye Angles'};
    writecell(labels_raw, excel_file, 'Sheet', 'Angles', 'Range', 'A2');
    writematrix(data, excel_file, 'Sheet', 'Angles', 'Range', 'A3');
    
    %Angular velocity sheet:
    labels_vel = {'Time (s)', 'Raw Left Eye Angular Velocity (deg/s)', ...
        'Raw Right Eye Angular Velocity (deg/s)', ...
        'Smoothed Left Eye Angular Velocity (deg/s)', ...
        'Smoothed Right Eye Angular Velocity (deg/s)', 'Left Gain', ...
        'Right Gain'};
    writecell(labels_vel, excel_file, 'Sheet', 'Ang Vel', 'Range', 'A2');
    writematrix(inst_ang_vel, excel_file, 'Sheet', 'Ang Vel', 'Range', 'A3');
   
    %Angular acceleration sheet:
    labels_vel = {'Time (s)', 'Raw Left Eye Angular Acceleration (deg/s^2)', ...
        'Raw Right Eye Angular Acceleration (deg/s^2)', ...
        'Smoothed Left Eye Angular Acceleration (deg/s^2)', ...
        'Smoothed Right Eye Angular Acceleration (deg/s^2)'};
    writecell(labels_vel, excel_file, 'Sheet', 'Ang Accel', 'Range', 'A2');
    writematrix(inst_ang_acc, excel_file, 'Sheet', 'Ang Accel', 'Range', 'A3');
    
    %Slow phase data sheet:
    labels_vel = {'Left Eye Time Vector (s)', 'Right Eye Time Vector (s)', 'Left Eye Angles (deg)',...
        'Right Eye Angles (deg)', 'Left Eye Instantaneous Velocity (deg/s)', ...
        'Right Eye Instantaneous Velocity (deg/s)', 'Left Eye Steady State Instantaneous Velocity (deg/s)',...
        'Right Eye Steady State Instantaneous Velocity (deg/s)', 'Left Eye Instantaneous Acceleration (deg/s^2)',...
        'Right Eye Instantaneous Acceleration (deg/s^2)'};
    writecell(labels_vel, excel_file, 'Sheet', 'Slow Phase Data', 'Range', 'A2');
    writematrix(slow_phase_matrix, excel_file, 'Sheet', 'Slow Phase Data', 'Range', 'A3');
    
    
   
end

